@startuml classes
set namespaceSeparator none
class "LamportProcess" as Lamport_timestamps.LamportProcess.LamportProcess {
  _id
  clock : int
  events_queue : Queue
  log : list
  main_thread : Thread
  message_queue : Queue
  processes : list[LamportProcess]
  start_time
  stop_worker : Event
  __init__(_id)
  enqueue_message(payload, clock)
  get_time()
  handle_event(payload, out_id) -> None
  increment_clock()
  inject_events(events: Queue) -> None
  main_loop()
  print_event(event_type: str, event_payload: str, event_time: float) -> None
  receive_message(payload, timestamp)
  send_message(to_process, payload)
  set_processes(processes) -> None
  start_loop(start_time)
}
@enduml
